sonar.projectKey=DiasPedroQA_Neutron_Star
sonar.projectName=Neutron Star
sonar.sourceEncoding=UTF-8

sonar.sources=Atoms/src
sonar.tests=Atoms/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=Atoms/coverage.xml
sonar.exclusions=**/__pycache__/**,**/.venv/**
sonar.coverage.exclusions=Atoms/tests/**
