sonar.projectKey=DiasPedroQA_Neutron_Star
sonar.projectName=Neutron Star
sonar.organization=diaspedro
sonar.sourceEncoding=UTF-8

sonar.sources=Atoms/src
sonar.tests=Atoms/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=Atoms/coverage.xml
sonar.exclusions=**/__pycache__/**,**/.venv/**
sonar.coverage.exclusions=Atoms/tests/**

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S8544
sonar.issue.ignore.multicriteria.e1.resourceKey=**/.github/workflows/docs.yml
