sonar.projectKey=DiasPedroQA_Neutron_Star
sonar.projectName=Neutron Star
sonar.organization=diaspedro
sonar.sourceEncoding=UTF-8

# Caminhos mapeados a partir da raiz do repositório
sonar.sources=Atoms/src
sonar.tests=Atoms/tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=Atoms/coverage.xml

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/templates/**,**/static/**
sonar.coverage.exclusions=Atoms/tests/**

# Ignora avisos específicos do GH Actions mapeados para os arquivos de workflow
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=githubactions:S8544
sonar.issue.ignore.multicriteria.e1.resourceKey=.github/actions/setup-python-env/action.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=githubactions:S7637
sonar.issue.ignore.multicriteria.e2.resourceKey=.github/workflows/ci-cd.yml
